import type { TradeModeId } from "./chatApi";

/**
 * Starters shown when a conversation is empty (no history to generate from).
 * ~50 per mode so picking 4 yields 230k+ unique combinations.
 */
export const STARTER_SUGGESTIONS: Record<TradeModeId, string[]> = {
  market_analysis: [
    "Summarize BTC structure on the 4h — am I in a range or trend?",
    "What should I watch if volatility is compressing before a move?",
    "How do I label HH/HL vs LH/LL on this type of chart?",
    "What does a liquidity sweep look like in practice?",
    "How do I map equal highs/lows and where stops often cluster?",
    "When does a trendline or channel mislead me — what to check instead?",
    "Explain market structure shift (MSS/BOS) in one example",
    "What are signs a range is resolving vs staying choppy?",
    "How do I read a volume profile to find high-value areas?",
    "What is a fair value gap and when should I expect it to fill?",
    "Walk me through how to identify an order block on the 1h chart",
    "BTC dominance is rising — what does that mean for alts right now?",
    "How do I use the VWAP as dynamic support/resistance intraday?",
    "Compare top-down analysis from weekly to 15m — what do I look for at each level?",
    "How do I distinguish accumulation from distribution in a range?",
    "What is a Wyckoff spring and how do I trade it?",
    "Explain the difference between displacement and normal candle movement",
    "When does divergence on RSI actually matter vs when it fakes out?",
    "How do I spot institutional candle patterns on higher timeframes?",
    "What key levels should I mark on Sunday before the week starts?",
    "Give me a pre-session checklist for analyzing BTC before I trade",
    "How do I use open interest alongside price to confirm a move?",
    "What does it mean when price sweeps a low then immediately reclaims?",
    "How do I tell if a breakout has real momentum or is running on fumes?",
    "What is the difference between a retracement and a reversal?",
    "How should I interpret long wicks on high-timeframe candles?",
    "Explain how HTF and LTF narratives can conflict and how to handle it",
    "What does healthy trending price action look like vs exhaustion?",
    "How do I identify a change of character (CHoCH) on the chart?",
    "What is a breaker block and how is it different from an order block?",
    "Walk me through analyzing ETH/BTC ratio to gauge alt season timing",
    "How do I use the 200 EMA as a trend filter across timeframes?",
    "What happens when price enters a previous day's value area?",
    "Explain how to use anchored VWAP from a swing high or low",
    "When should I pay attention to CME gaps in BTC?",
    "How do I analyze the monthly candle close for a directional bias?",
    "What is a mitigation block and when does price react to it?",
    "How do I read the delta between spot and perp prices?",
    "What does it mean when volume declines during a rally?",
    "Give me a framework for mapping swing failure patterns",
    "How do I combine Fibonacci retracements with order flow for confluence?",
    "What is smart money reversal and how do I spot it forming?",
    "How should I interpret the put/call ratio in crypto options?",
    "What does a bearish engulfing on the weekly actually signal?",
    "When is a double bottom a trap instead of a reversal signal?",
    "How do I use session highs and lows for intraday trading?",
    "What is a liquidity void and how does price behave inside one?",
    "Explain how to use market profile for identifying balance vs imbalance",
    "How do I analyze BTC correlation with the S&P 500 or DXY?",
    "What does it mean when the weekly close is above the yearly open?",
  ],
  trade_signals: [
    "Outline a scalp framework: entry, stop, target, invalidation",
    "What makes a breakout setup valid vs a fakeout?",
    "Compare swing vs futures execution risks I should watch",
    "When should I label a setup 'No Trade' for a late entry?",
    "Give a checklist for a pullback continuation vs a reversal",
    "How do I set a stop beyond obvious liquidity without being silly wide?",
    "What is a minimum R:R you'd accept for this style of setup?",
    "How do I handle partial fills or slippage in fast markets?",
    "Build a trade plan template: bias, trigger, entry, stop, targets",
    "When is it better to market-order in vs wait for a limit fill?",
    "Give me 3 clean entry techniques for a trend continuation trade",
    "How do I trail a stop on a winning trade without getting chopped?",
    "What is a re-entry setup after I get stopped out of a valid idea?",
    "Walk me through scaling into a position vs going all-in at once",
    "How do I manage a trade when price goes sideways after entry?",
    "What should I do when my target is hit but momentum is still strong?",
    "Give a framework for taking partials at key levels",
    "How do I read the tape (time & sales) for a scalp entry?",
    "When should I flip bias intraday and what confirms the flip?",
    "What is the best way to journal a trade setup for later review?",
    "How do I trade a retest of a broken structure level?",
    "Give a checklist for a short setup after a failed breakout",
    "When does a gap-fill setup have high probability vs low?",
    "How should I adjust stops and targets in low-liquidity sessions?",
    "What is a sniper entry and when is it worth waiting for one?",
    "How do I decide between a market, limit, or stop-limit order?",
    "Walk me through a momentum ignition trade from start to finish",
    "What are warning signs that a setup is too crowded?",
    "How do I trade a liquidity grab at a key level?",
    "Give me a framework for trading the London session open",
    "What is a turtle soup reversal setup and when does it work?",
    "How do I trade a mean-reversion bounce at a standard deviation band?",
    "Walk me through fading a blow-off top with proper risk",
    "How do I set up alerts so I don't miss an entry while away?",
    "What is a 2B reversal pattern and how do I trade it?",
    "Give me an execution plan for trading an ascending triangle breakout",
    "How do I trade the first pullback after a trend break?",
    "When should I hold through consolidation vs cut and re-enter?",
    "Walk me through a range-breakout-retest trade on the 15m",
    "How do I use time-of-day filters to improve my signal quality?",
    "What is a Quasimodo reversal pattern and how do I spot it?",
    "Give me a framework for pyramiding into a winning position",
    "How do I identify the best time window for scalping crypto?",
    "What is the difference between a sweep and a break of structure?",
    "How do I trade an inside bar breakout on the daily?",
    "Give me a pre-trade checklist I can run in 60 seconds",
    "How do I use funding rate extremes as a contrarian signal?",
    "Walk me through trading a V-reversal from liquidation cascade",
    "What is a stop-run reversal and how do I confirm it's real?",
    "How do I manage a trade overnight without setting a hard stop too tight?",
  ],
  strategy: [
    "Help me write explicit entry and exit rules for a trend strategy",
    "How do I define failure conditions before I trade a system live?",
    "What is a simple way to think about sample size and overfitting?",
    "Give a checklist for reviewing a strategy each week",
    "How do I decide trade frequency vs expectancy for my schedule?",
    "What's a clean way to log setups so I can review them monthly?",
    "How should I think about regime change invalidating my rules?",
    "Draft a simple hypothesis: edge, timeframe, and falsification test",
    "Help me design a mean-reversion strategy for range-bound markets",
    "What is walk-forward optimization and why does it matter?",
    "How do I build a simple scoring system for my setups?",
    "Compare rules-based vs discretionary trading — which fits me?",
    "How do I test a strategy idea without coding a full backtest?",
    "What is the difference between edge decay and bad execution?",
    "Give me a framework for combining two indicators without curve-fitting",
    "How should I handle a strategy that works in backtests but fails live?",
    "When is it time to stop tweaking a strategy and commit to it?",
    "Help me write a strategy mandate: what I will and won't trade",
    "What is Monte Carlo analysis and how does it help evaluate a strategy?",
    "How do I build a strategy around session opens (London, NY, Asia)?",
    "Design a breakout strategy with specific entry/exit/filter rules",
    "What role does a regime filter play and how do I create one?",
    "How do I adapt a daily strategy to work on the 4h timeframe?",
    "Give me a template for documenting a strategy before going live",
    "How many trades do I need before I trust my backtest results?",
    "What metrics besides win rate actually tell me if my strategy is good?",
    "How do I benchmark my strategy against buy-and-hold?",
    "Walk me through building a simple trend-following system step by step",
    "How do I create a portfolio of uncorrelated strategies?",
    "What is out-of-sample testing and why is it critical?",
    "Give me a framework for a momentum-based altcoin rotation strategy",
    "How do I decide if I should automate my strategy or keep it manual?",
    "What is survivorship bias and how does it affect my backtest?",
    "Help me design a strategy that uses volatility expansion as a trigger",
    "How do I create proper entry and exit rules for a range-trading system?",
    "What is the difference between strategy alpha and market beta?",
    "How should I handle overnight gaps in a mean-reversion system?",
    "Give me a framework for a funding-rate arbitrage strategy",
    "How do I evaluate whether my strategy is robust vs overfit?",
    "What is a lookback bias and how do I avoid it in my rules?",
    "Help me build a scalping system using order flow and price action",
    "How do I design a strategy that works in both bull and bear markets?",
    "What is a composite strategy and when should I use one?",
    "Give me a method for systematically tracking strategy performance",
    "How do I know if I should add a new rule or remove an existing one?",
    "Walk me through building a pairs trading strategy in crypto",
    "What is Sharpe ratio and what number should I aim for?",
    "How do I rotate between strategies based on market conditions?",
    "Give me a framework for journaling strategy experiments",
    "How should I think about adding a discretionary overlay to a systematic strategy?",
  ],
  risk_management: [
    "How do I size a position if I risk 1% per trade?",
    "What is portfolio heat and how do I cap it?",
    "When is leverage turning a good setup into unacceptable risk?",
    "How should I think about max drawdown and cooldown rules?",
    "How do I scale size up or down after winning/losing streaks?",
    "What's a sane way to cap daily and weekly loss limits?",
    "How do correlated alt positions inflate risk without me noticing?",
    "Explain notional vs margin risk in one practical scenario",
    "How do I calculate my true risk when I have multiple open positions?",
    "What is a risk budget and how do I allocate it across trades?",
    "Give me a position sizing formula that accounts for volatility",
    "How should I adjust risk when moving from paper to live trading?",
    "What is the Kelly criterion and should I actually use it?",
    "How do I protect my account during high-impact news events?",
    "Walk me through setting a max loss rule for the month",
    "When should I reduce my position size vs stop trading entirely?",
    "How do I think about risk-reward when adding to a winning position?",
    "What is a risk-off protocol and how do I design one?",
    "How do I account for gap risk and weekend exposure in crypto?",
    "Give me a framework for deciding when to use leverage vs spot",
    "How do I set stop losses in a volatile market without being silly tight?",
    "What happens to my portfolio risk if BTC drops 20% overnight?",
    "How should I risk-manage a hedge vs a directional trade?",
    "Walk me through diversification in a crypto-only portfolio",
    "How do I track my risk metrics on a daily basis?",
    "What is value at risk (VaR) in simple terms and should I use it?",
    "How do I know if my drawdown is within normal variance or a real problem?",
    "Give me a circuit breaker rule set to protect my capital",
    "How do I calculate the dollar risk of a leveraged perpetual position?",
    "What is the right way to risk-manage a grid or DCA bot?",
    "How should I think about liquidation price vs stop-loss price?",
    "Give me a formula for adjusting position size based on ATR",
    "What is a risk parity approach and can I apply it to crypto?",
    "How do I measure and limit my overall portfolio delta?",
    "Walk me through building a personal risk dashboard in a spreadsheet",
    "When should I use options or hedges instead of reducing size?",
    "How do I evaluate risk when I'm in both spot and futures at the same time?",
    "What is tail risk and how do I protect against a black swan event?",
    "How should I change my risk rules during extreme market fear or greed?",
    "Give me a step-by-step plan for recovering from a 30% drawdown",
    "How do I factor in exchange counterparty risk for my portfolio?",
    "What is the difference between fixed fractional and fixed ratio sizing?",
    "How should I think about opportunity cost as a form of risk?",
    "When does adding more positions help vs hurt my risk profile?",
    "How do I stress-test my portfolio against historical crash scenarios?",
    "Give me a rule set for when to pull funds off an exchange",
    "How do I manage risk when trading across multiple exchanges?",
    "What is my true max loss if the network or exchange goes down?",
    "How should I split my portfolio between active trading and cold storage?",
    "Give me a monthly risk audit checklist I can follow every month",
  ],
  trader_psychology: [
    "I chased a move after a loss — walk me through the correction",
    "Give a 5-step pre-trade routine to reduce FOMO",
    "How do I spot revenge trading early and stop it?",
    "Reframe outcome focus into process focus for this week",
    "I broke my plan twice today — what should I do before tomorrow?",
    "How do I handle FOMO when price runs without me?",
    "Give language I can use to debrief a bad trade without shame",
    "What are early warning signs I'm trading on tilt?",
    "How do I build confidence after a losing streak without being reckless?",
    "What does a healthy relationship with trading losses look like?",
    "Give me a meditation or breathing exercise for mid-session stress",
    "How do I avoid checking charts obsessively after I enter a trade?",
    "What's the difference between discipline and rigidity in trading?",
    "How do I handle the urge to move my stop loss when price is near it?",
    "Design a post-trade review ritual that actually helps me improve",
    "I'm afraid to take the next trade after a big loss — what do I do?",
    "How do I separate my self-worth from my P&L?",
    "What cognitive biases hit traders hardest and how do I counter them?",
    "Give me a plan for my first 30 minutes when I sit down to trade",
    "How do I stay patient waiting for a setup instead of forcing trades?",
    "What should my 'rules for when to walk away' look like?",
    "How do I deal with regret after missing a big move?",
    "What is analysis paralysis and how do I push through it?",
    "Help me write a personal trading creed or set of values",
    "How do I maintain focus during a boring, low-volatility session?",
    "What can I learn from sports psychology to improve my trading?",
    "How do I recover mentally after blowing a significant portion of my account?",
    "Give me a framework for evaluating if I'm in the right state to trade today",
    "How do I stop overtrading when I feel behind on my goals?",
    "What is the sunk cost fallacy in trading and how do I escape it?",
    "Give me a visualization technique I can use before a trading session",
    "How do I deal with boredom-driven trades during quiet markets?",
    "What does an ideal wind-down routine look like after trading?",
    "How do I reframe a bad losing week without it destroying my confidence?",
    "What is the Dunning-Kruger effect and how does it hurt new traders?",
    "How do I handle social pressure when others show huge gains?",
    "Give me journal prompts for my trading psychology review",
    "How do I build a growth mindset specifically for trading?",
    "What role does sleep and physical health play in trading performance?",
    "How do I handle the emotional conflict of scaling up size?",
    "What is decision fatigue and how do I minimize it while trading?",
    "Give me a framework for celebrating process wins, not just profit",
    "How do I stop comparing my results to other traders on social media?",
    "What are grounding techniques I can use after a stressful trade?",
    "How do I develop emotional awareness without being paralyzed by it?",
    "Give me a pre-market mental checklist like a pilot would use",
    "How do I handle the anxiety of holding a position overnight?",
    "What is the difference between healthy caution and fear-based avoidance?",
    "How do I stay motivated during a long sideways equity curve?",
    "Give me a 5-day challenge to improve my trading habits this week",
  ],
  news_sentiment: [
    "How do I separate narrative hype from real catalyst impact?",
    "What questions should I ask about a regulatory headline?",
    "How can sentiment be bullish in headlines but fragile in price?",
    "Template for analyzing a macro print vs crypto reaction",
    "How do I tell if bad news is already priced in?",
    "What red flags suggest a headline is noise for my timeframe?",
    "How should I weight on-chain flows vs social sentiment?",
    "Give a quick framework for earnings-like events in crypto",
    "How do I read Crypto Twitter without being manipulated by it?",
    "What does it mean when funding rates diverge from price direction?",
    "How should I interpret exchange inflow/outflow spikes?",
    "Give me a checklist for evaluating a new token listing announcement",
    "How do I trade a Fed rate decision — before, during, or after?",
    "What on-chain metrics matter most for gauging whale activity?",
    "How do I assess if a partnership announcement has real value?",
    "When does a hack or exploit create a buying opportunity vs a death spiral?",
    "How should I react to a sudden large liquidation cascade in the news?",
    "What is the typical lifecycle of a crypto narrative and how do I time it?",
    "Give me a framework for evaluating macro news impact on BTC",
    "How do I distinguish genuine fear from manufactured FUD?",
    "What social sentiment tools should I consider and how do I read them?",
    "How do I interpret CPI/PPI/jobs data for crypto positioning?",
    "When does a stablecoin depeg become systemic risk vs a blip?",
    "How should I think about geopolitical risk affecting crypto markets?",
    "What is the 'buy the rumor, sell the news' pattern and when does it fail?",
    "How do I evaluate the impact of mining difficulty adjustments?",
    "Give me a process for scanning headlines each morning efficiently",
    "How do ETF flow data and institutional reports affect my short-term bias?",
    "How do I interpret a large wallet moving coins to an exchange?",
    "What is a narrative rotation and how do I position early in one?",
    "Give me a checklist for evaluating a new regulatory proposal",
    "How does a FOMC minutes release differ from a rate decision in market impact?",
    "What is reflexivity in crypto markets and how does narrative drive price?",
    "How should I trade around a major protocol upgrade or hard fork?",
    "Give me a framework for measuring crowd euphoria vs despair",
    "How do stablecoin mint/burn data help me gauge institutional demand?",
    "What is the relationship between BTC ETF inflows and spot price?",
    "How do I use the Commitment of Traders report for crypto context?",
    "When does a whale accumulation signal actually precede a move?",
    "How should I interpret a spike in Google Trends for 'Bitcoin'?",
    "Give me a framework for trading during a major airdrop event",
    "What happens to altcoin narratives when BTC enters a strong trend?",
    "How do I evaluate if a token burn announcement is meaningful?",
    "What is the typical pattern after a major exchange listing?",
    "How do I read on-chain profit/loss metrics like NUPL or SOPR?",
    "Give me a template for writing a weekly market narrative summary",
    "How do I evaluate the credibility of anonymous crypto sources?",
    "What role does the DXY (dollar index) play in crypto sentiment?",
    "How should I position around a known macro event calendar day?",
    "Give me a framework for detecting when a narrative is exhausted",
  ],
  education: [
    "Explain funding rates in plain language with a simple example",
    "What is open interest and why do traders care?",
    "Walk through support, resistance, and retests",
    "What is the difference between spot and perpetual futures?",
    "What is basis and when does it matter for my trade?",
    "Explain liquidation cascades in simple terms",
    "What is delta vs gamma in one intuitive paragraph?",
    "How do order books and depth affect short-term moves?",
    "What is slippage and how does it eat into my profits?",
    "Explain the concept of liquidity in crypto markets",
    "What are maker and taker fees and how do they affect my strategy?",
    "Walk through how a limit order book works step by step",
    "What is an AMM and how is it different from an order book?",
    "Explain the difference between cross margin and isolated margin",
    "What are Bollinger Bands and when are they useful?",
    "How does a moving average crossover strategy work?",
    "What is the difference between realized and unrealized P&L?",
    "Explain what a short squeeze is with a real-world example",
    "What is the Fear & Greed Index and should I use it?",
    "How do candlestick patterns work — which ones actually matter?",
    "What is the difference between a CEX and a DEX?",
    "Explain impermanent loss in DeFi liquidity providing",
    "What is dollar-cost averaging and when is it the right approach?",
    "How do stablecoins maintain their peg and what can go wrong?",
    "What is a flash loan and why does it matter for DeFi security?",
    "Explain the difference between Layer 1 and Layer 2 in simple terms",
    "What is TVL (Total Value Locked) and why do people track it?",
    "Walk me through what happens when I place a market order on an exchange",
    "What is an oracle and why is it essential for DeFi protocols?",
    "Explain the concept of MEV (miner extractable value) simply",
    "What is a token vesting schedule and how does it affect price?",
    "How do blockchain bridges work and what are the risks?",
    "What is the difference between ERC-20, BEP-20, and SPL tokens?",
    "Explain what yield farming is and how APY is calculated",
    "What is a rug pull and how do I spot the warning signs?",
    "How does a lending protocol like Aave or Compound work?",
    "What is the difference between a hard fork and a soft fork?",
    "Explain proof of work vs proof of stake in plain language",
    "What are gas fees and why do they change so much?",
    "How does a decentralized exchange handle large orders?",
    "What is the difference between a limit order and a stop order?",
    "Explain the concept of margin call and when it triggers",
    "What are perpetual swaps and why are they popular in crypto?",
    "How do crypto derivatives differ from traditional derivatives?",
    "What is the difference between market cap and fully diluted valuation?",
    "Explain what a liquidity pool is and how LPs earn fees",
    "What is on-chain analysis and how does it differ from technical analysis?",
    "How do staking rewards work and what is the risk?",
    "What is a governance token and why would I want one?",
    "Explain the concept of token burns and how they affect supply",
  ],
  safe_binance_trading_bot: [
    "Review my step list: open → add margin → close — is the order valid?",
    "If 'close at 110' is after 'add margin at 90' but price hits 110 first, what happens?",
    "Explain strict step execution vs price-only triggers on this platform",
    "How do I sequence add-margin steps so nothing stays blocked?",
    "Validate this setup: open long, add margin at +1%, close at +5%",
    "What is a blocked-action scenario in step trading here?",
    "Compare 200% vs 300% reverse strategy exposure at the same leverage",
    "Walk through short-side scaling when price rises 101%, 102%, 104%, 106%",
    "Explain minimum bound logic and why we do not close immediately on a dip",
    "When should I worry about exponential margin adds in a strong trend?",
    "Estimate how fast margin demand grows if each level doubles exposure",
    "What liquidation risks appear at 100x with tiny initial margin each side?",
    "How does choppy price action interact with step order and bound rules?",
    "If price rises fast through levels, what execution risks should I list?",
    "Draft a System Check for my pasted step configuration",
    "What does 'Invalid' vs 'Needs Adjustment' mean for my step plan?",
    "How do I explain outcomes in a rising market before suggesting changes?",
    "Simulate: price reaches my close trigger before an earlier add-margin step",
    "What safer alternatives exist if margin growth is outpacing my cushion?",
    "List critical levels I should monitor for a 200% reverse grid idea",
    "How do I think like an execution validator when reviewing user steps?",
    "What questions should I ask if the user omits leverage and margin size?",
    "Explain cascading liquidation risk in one structured paragraph",
    "Why must I warn: this strategy fails in strong trends?",
    "Why must I warn: this setup risks liquidation before reversal?",
    "How do I format the Final Verdict line for a borderline setup?",
    "What belongs under Execution Risk vs Blocked Actions?",
    "How does total exposure at 100% both sides change after each add?",
    "Give a checklist for reviewing a 300% strategy under high leverage",
    "What is wrong with assuming unlimited capital in reverse scaling?",
    "How should I phrase risk without hype or profit guarantees?",
    "User has long and short both open with $1 each at 100x — assess risks",
    "How do I validate that later steps cannot run before earlier ones complete?",
    "What does 'monitor trend reversal' mean practically after a bound break?",
    "Compare behavior if price stays above bound vs drops below bound",
    "What optimization section should I fill when step order is invalid?",
    "How do I highlight when an action cannot execute under current rules?",
    "Give an example of invalid step logic I should catch immediately",
    "How do margin doubling rules change my exposure curve vs linear adds?",
    "What market scenario section should I use for a range-bound user?",
    "How do I merge system mechanics advice with generic TA safely?",
    "What leverage-specific warnings should almost always appear?",
    "User wants aggressive scaling — how do I refuse reckless martingale tone?",
    "How do I prioritize capital preservation in every answer structure?",
    "What is the difference between execution order and price priority here?",
    "How should I respond if the user pastes only prices without step types?",
    "Give a template System Check for a minimal user message",
    "What pro questions uncover missing margin capacity and max pain?",
    "How do I state uncertainty about venue-specific fees without guessing?",
  ],
  cryptdocker: [
    "Assess this domain risk: is this exchange URL trustworthy?",
    "I have conflicting signals across tabs - what should I prioritize now?",
    "Summarize today's highest-signal crypto news and likely market impact",
    "Check this setup for contradiction: bullish entry but negative macro narrative",
    "Which open tabs are likely noise versus decision-critical right now?",
    "Analyze this alert stream and rank urgent vs low-priority actions",
    "Give me a quick workspace optimization to reduce context switching errors",
    "Evaluate phishing risk for this wallet connection request",
    "How should I balance opportunity vs risk for this fast-moving setup?",
    "Convert these mixed signals into one actionable next step",
    "Is this token launch headline tradable signal or mostly hype?",
    "Assess trust score for this protocol and list key risk factors",
    "Build a short decision checklist before I place this trade",
    "I am overloaded with tabs - propose a cleaner workflow by priority",
    "Interpret this alert: price spike, social buzz, and funding jump together",
    "What hidden risks might I be missing across my current workspace?",
    "Give a risk-first read on this potential breakout trade",
    "Which narrative is strongest right now and how long might it persist?",
    "Review these platform actions for conflict before execution",
    "Flag warning signs that this website may be a scam clone",
    "Separate short-term noise from long-term signal in this news flow",
    "Should I focus on protecting downside or pressing this opportunity?",
    "Provide a Trust Score and recommendation for this dApp domain",
    "How do I avoid mistakes when switching between exchange and wallet tabs?",
    "What is the safest next action based on current market and news context?",
    "Detect contradictions in my plan and suggest a clearer priority",
    "How should I triage alerts when multiple platforms fire at once?",
    "Give me a concise risk report for this contract address",
    "What is the expected impact of this headline over 24h vs 2 weeks?",
    "Help me reduce decision fatigue in my current trading workflow",
    "Analyze this platform announcement for credibility and likely impact",
    "What focus area gives the best signal-to-noise right now?",
    "Assess whether this opportunity is worth the operational risk",
    "Turn these scattered tab observations into one clear action plan",
    "Is my current workspace setup increasing execution mistakes?",
    "Rank these open tasks by safety, clarity, and market urgency",
    "Evaluate this exchange withdrawal alert for potential security risk",
    "How should I respond when bullish charts conflict with bearish news?",
    "Give me a low-noise briefing of what actually matters right now",
    "Can you identify probable scam indicators in this project page?",
    "What should I ignore immediately to stay focused on high-impact signals?",
    "Assess short-term trade bias with explicit risk notes and caveats",
    "Build a quick workspace protocol for volatile news events",
    "Review this token narrative: strong catalyst or fading story?",
    "What operational mistake is most likely in my current flow?",
    "Help me prioritize safety before profitability on this setup",
    "Provide a concise Risk Analysis Mode response for this domain",
    "Provide a News Insight Mode response for these headlines",
    "Provide a Trading Insight Mode response for this market context",
    "Provide a Workspace Optimization Mode response for my tab overload",
  ],
};

const STARTER_DISPLAY_COUNT = 4;

function hashToUint32(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** Deterministic shuffle indices using seed string (Fisher-Yates with LCG). */
function shuffledIndices(length: number, seed: string): number[] {
  const idx = Array.from({ length }, (_, i) => i);
  let state = hashToUint32(seed);
  for (let i = length - 1; i > 0; i--) {
    state = (Math.imul(state, 1103515245) + 12345) >>> 0;
    const j = state % (i + 1);
    const t = idx[i]!;
    idx[i] = idx[j]!;
    idx[j] = t;
  }
  return idx;
}

function pickFromPool(pool: string[], count: number, seed: string): string[] {
  const n = Math.min(count, pool.length);
  if (n <= 0) return [];
  const order = shuffledIndices(pool.length, seed);
  const out: string[] = [];
  for (let k = 0; k < n; k++) {
    out.push(pool[order[k]!]!);
  }
  return out;
}

/** Empty-thread chips: stable for this chat + mode, different across conversations. */
export function pickStarterSuggestions(
  mode: TradeModeId,
  conversationId: string
): string[] {
  return pickFromPool(
    STARTER_SUGGESTIONS[mode],
    STARTER_DISPLAY_COUNT,
    `starters|${conversationId}|${mode}`
  );
}
